name: scansion
channels:
 - defaults
 - conda-forge
dependencies:
 - black=22.3.0
 - flake8=3.9.2
 - make=4.2.1
 - mypy=0.910
 - protobuf=3.17.2
 - pynini=2.1.5
 - pytest=6.2.4
 - python=3.9.7
 - setuptools=58.0.4
 - thrax=1.3.8
