name: scansion
channels:
 - defaults
 - conda-forge
dependencies:
 - black=22.3.0
 - flake8=5.0.4
 - make=4.3
 - mypy=1.9.0
 - protobuf=3.20.3
 - pynini=2.1.6
 - pytest=8.1.1
 - python=3.9.13
 - setuptools=69.5.1
 - thrax=1.3.9
