name: scansion
channels:
 - defaults
 - conda-forge
dependencies:
 - black=24.4.2
 - build=0.7.0
 - flake8=7.1.1
 - hatch=1.12.0
 - make=4.3
 - mypy=1.11.1
 - protobuf=4.25.3
 - pynini=2.1.6.post1
 - pytest=8.3.2
 - python>=3.8
 - thrax=1.3.9
