name: scansion
channels:
 - defaults
 - conda-forge
dependencies:
 - black=22.3.0
 - flake8=4.0.1
 - make=4.2.1
 - mypy=0.910
 - protobuf=3.20.1
 - pynini=2.1.5
 - pytest=7.1.2
 - python=3.9.7
 - setuptools=65.5.1
 - thrax=1.3.8
