version: 2.1


jobs:
  pre-build:
    description: A check that needs to be done on only one supported Python
    parameters:
      command-run:
        type: string
    docker:
    - image: cimg/python:3.12.1
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_ACCESS_TOKEN
    steps:
    - checkout
    - run:
        command: pip install -r requirements.txt
    - run:
        command: << parameters.command-run >>

  build-python:
    parameters:
      python-version:
          type: string
    docker:
    - image: cimg/python:<< parameters.python-version >>
    steps:
    - checkout
    - run:
        name: Build Thrax grammars
        command: |
            conda env create --quiet --file environment.yml
            source ~/.bashrc
            conda activate scansion
            make -j -C grammars
            make -C latin_scansion
    - run:
        name: Build source distribution and install package from it
        command: |
            pip install --progress-bar off --requirements requirements.txt
            python -m build
            pip install dist/`ls dist/ | grep .whl`
    - run:
        name: Show installed Python packages
        command: pip list -v
    - run:
        name: Run tests
        command: pytest -vv tests --junitxml /tmp/testxml/report.xml
    - store_test_results:
        path: /tmp/testxml/

workflows:
  version: 2
  build:
    jobs:
    - pre-build:
        name: black
        command-run: black --line-length=79 --check --exclude latin_scansion/scansion_pb2.py latin_scansion tests
    - pre-build:
        name: flake8
        command-run: flake8 --exclude latin_scansion/scansion_pb2.py latin_scansion tests
    - pre-build:
        name: twine
        command-run: |
            python -m build && \
            twine check dist/`ls dist/ | grep .tar.gz` && \
            twine check dist/`ls dist/ | grep .whl`"
    - build-python:
        matrix:
          parameters:
            python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        requires:
        - black
        - flake8
        - twine
